#!/bin/bash
QT_BASE_DIR=/opt/qt52
if [[ $(uname -m) == "x86_64" ]]; then
  export LD_LIBRARY_PATH=$QT_BASE_DIR/lib/x86_64-linux-gnu:$QT_BASE_DIR/lib:$LD_LIBRARY_PATH
else
  export LD_LIBRARY_PATH=$QT_BASE_DIR/lib/i386-linux-gnu:$QT_BASE_DIR/lib:$LD_LIBRARY_PATH
fi
export LD_LIBRARY_PATH=/opt/board:$LD_LIBRARY_PATH
exec `echo $0 | sed s/-wrapper//` $*

